services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    container_name: skyjo-frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: skyjo-backend
    environment:
      - DB_HOST=mysql
      - DB_USER=olivier
      - DB_PASSWORD=olivier
      - DB_NAME=skyjo
    depends_on:
      - mysql
    networks:
      - skyjo-db_network

  mysql:
    image: mysql:latest
    container_name: skyjo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: olivier
      MYSQL_DATABASE: skyjo
      MYSQL_USER: olivier
      MYSQL_PASSWORD: olivier
    ports:
      - "3306:3306"
    volumes:
      - skyjo-mysql_data:/var/lib/mysql
    networks:
      - skyjo-db_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: skyjo-phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: olivier
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - skyjo-db_network

volumes:
  skyjo-mysql_data:

networks:
  skyjo-db_network:
